### PR TITLE
Inject version picker JavaScript during build.

### PR DESCRIPTION
**Pull request by acolomb**
This is based on (and includes the commits from) #1.

Apply a patch to add the _static/version_redirect.js file just before rebuilding.  This way it will end up being included in all generated HTML files.  Rebuild all historic versions with the patch applied.

Add Makefile rule for copying only and updated JS file instead of rebuild for future modifications.

### CODE REVIEW

**Comment by acolomb** [comment]
Please keep commits separate when merging / rebasing.

If we want to avoid the mass-rebuild, 4f0792e could be isolated and applied to the `main` branch directly.  But I'd prefer to get a clean slate first.  It won't really affect build times on the main docs repo, because the `netlify-build.sh` script specifies `--depth 1` for cloning this.  So all the outdated objects won't even be transferred.

This should be merged before https://github.com/syncthing/docs/pull/721, so the latter picks up the updated files here during deployment.

**Comment by acolomb** [comment]
@calmh I was hoping to get this done before the final v1.19.0 release.  Any chance you could look into it soon?

**Comment by calmh** [comment]
There's no rush. This is a bit cumbersome to even glance at, what with the 8500 changed files and my browser stalling when loading the files tab. I would think that it would be better to include this functionality directly in the docs repo instead of via a patch, and do a one time rebuild of old versions using whatever hacky method once?

**Comment by acolomb** [comment]
> This is a bit cumbersome to even glance at, what with the 8500 changed files and my browser stalling when loading the files tab.

That's exactly why I separated the changes and #1 is exactly that one-time rebuild *without* any changes but using a clearly documented (and therefore reproducible) build environment.  For this function alone, the last commit contains all the relevant changes.  The two before that are just tooling to document how that state was reached.  For which #1 was a prerequisite to keep the diff small.  Best use the commit view instead of the files tab, which by default loads all commits.

> I would think that it would be better to include this functionality directly in the docs repo instead of via a patch, and do a one time rebuild of old versions using whatever hacky method once?

That's actually what I did.  https://github.com/syncthing/docs/pull/721 has the original change, which will continue to be maintained there.  The patch here is just for backporting once.  The reason for adding the Makefile is to document what has been patched mainly, and to ease in generating new builds until it's finalized.  No intention to run any build command here on a regular basis.

So I suggest to merge #1 "blindly", trusting I really just did the rebuild using the documented setup.  Then this PR will only add three small commits on top.  That's why it's important to not squash-merge in this case.  I will force-push this branch with refined versions of the patch (and particularly its results).

**Comment by acolomb** [comment]
Since v1.19.0 included a previous state of `_static/version_redirect.js`, I had to switch from using a single patch file here to a series of smaller patches.  The first being what has been included between v1.18.6 and v1.19.0.  This will be more robust if any part needed to be rebuilt later.

So this now effectively includes #3 as well, but I should better rebase when that is merged / obsoleted by a bot commit.  Mind any differences in build environments though, we should probably avoid mixing them.

**Comment by calmh** [comment]
Feel free to merge after appropriate rebasing etc, I think I fixed the permissions, it was unintentionally restrictive for this repo.

**Pull request merged**
